name: weather_forecast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  http: ^1.2.2
  intl: ^0.19.0
  loading_animation_widget: ^1.3.0
  mobx: ^2.4.0
  mobx_codegen: ^2.6.2
  timezone: ^0.10.0
  weather: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
